version: "3"

services:

  devcontainer:
    container_name: dapr_devcontainer
    image: daprdev:latest
    build:
      context: .
    depends_on:
      - redis
      - dapr-placement
    ports:
      - "5000:5000"
      - "5001:5001"
      - "6001:6001"
    networks:
      - daprdev
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 

  dapr-placement:
    container_name: daprdevcontainer_placement
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - daprdev

  redis:
    container_name: daprdevcontainer_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - daprdev

  loadtest:
    container_name: daprdevcontainer_loadtest
    image: locustio/locust
    build:
      context: ./loadtest
    ports:
      - "8089:8089"
    networks:
      - daprdev
  
networks:
  daprdev:
